### ISSUE TITLE
Use NixOS stable by default

### ISSUE THREAD

**Issue by jalil-salame** [jalil-salame/configuration.nix#22]
Select packages from unstable when appropriate, but keep most of the system in
the stable channel (including home-manager). This improves the system stability
while still having some packages be bleeding edge (`gitoxide` is the only one
that comes to mind right now).

> [!Note]
> Probably wait until 24.05 is in beta before starting this, as currently most
> packages in stable are outdated and switching back may cause issues.

TODO:

- [x] Change NixVim channel to stable (#19)
- [x] Change default channel to stable (#77)
- [x] Change home-manager channel to stable (#77)
- [x] Add an overlay that introduces packages from the `unstable` channel (#77)
